set_property SRC_FILE_INFO {cfile:D:/repos/RFSoC_GTY/gtwizard_ultrascale_0_ex/imports/gtwizard_ultrascale_0_example_top.xdc rfile:../../../imports/gtwizard_ultrascale_0_example_top.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property package_pin V35 [get_ports mgtrefclk0_x0y2_n]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property package_pin V34 [get_ports mgtrefclk0_x0y2_p]
