# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/repos/RFSoC_GTY/vivado_project/RFSoC_GTY.srcs/sources_1/bd/top_level_block/ip/top_level_block_axis_data_fifo_0_1/top_level_block_axis_data_fifo_0_1.xci
# IP: The module: 'top_level_block_axis_data_fifo_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/repos/RFSoC_GTY/vivado_project/RFSoC_GTY.gen/sources_1/bd/top_level_block/ip/top_level_block_axis_data_fifo_0_1/top_level_block_axis_data_fifo_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_block_axis_data_fifo_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/repos/RFSoC_GTY/vivado_project/RFSoC_GTY.srcs/sources_1/bd/top_level_block/ip/top_level_block_axis_data_fifo_0_1/top_level_block_axis_data_fifo_0_1.xci
# IP: The module: 'top_level_block_axis_data_fifo_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/repos/RFSoC_GTY/vivado_project/RFSoC_GTY.gen/sources_1/bd/top_level_block/ip/top_level_block_axis_data_fifo_0_1/top_level_block_axis_data_fifo_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_block_axis_data_fifo_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
