# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/repos/RFSoC_GTY/gtwizard_ultrascale_0_ex/imports/gtwizard_ultrascale_0_example_top.xdc

# IP: ip/gtwizard_ultrascale_0/gtwizard_ultrascale_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gtwizard_ultrascale_0 || ORIG_REF_NAME==gtwizard_ultrascale_0} -quiet] -quiet
