# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/des_const.xdc

# Block Designs: bd/top_level_block/top_level_block.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_block || ORIG_REF_NAME==top_level_block} -quiet] -quiet

# IP: bd/top_level_block/ip/top_level_block_zynq_ultra_ps_e_0_0/top_level_block_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_block_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==top_level_block_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/top_level_block/ip/top_level_block_axi_gpio_0_0/top_level_block_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_block_axi_gpio_0_0 || ORIG_REF_NAME==top_level_block_axi_gpio_0_0} -quiet] -quiet

# IP: bd/top_level_block/ip/top_level_block_axi_gpio_1_0/top_level_block_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_block_axi_gpio_1_0 || ORIG_REF_NAME==top_level_block_axi_gpio_1_0} -quiet] -quiet

# IP: bd/top_level_block/ip/top_level_block_axis_data_fifo_0_0/top_level_block_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_block_axis_data_fifo_0_0 || ORIG_REF_NAME==top_level_block_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/top_level_block/ip/top_level_block_proc_sys_reset_0_0/top_level_block_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_block_proc_sys_reset_0_0 || ORIG_REF_NAME==top_level_block_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/top_level_block/ip/top_level_block_axis_data_fifo_0_1/top_level_block_axis_data_fifo_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_block_axis_data_fifo_0_1 || ORIG_REF_NAME==top_level_block_axis_data_fifo_0_1} -quiet] -quiet

# IP: bd/top_level_block/ip/top_level_block_xbar_0/top_level_block_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_block_xbar_0 || ORIG_REF_NAME==top_level_block_xbar_0} -quiet] -quiet

# IP: bd/top_level_block/ip/top_level_block_auto_ds_0/top_level_block_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_block_auto_ds_0 || ORIG_REF_NAME==top_level_block_auto_ds_0} -quiet] -quiet

# IP: bd/top_level_block/ip/top_level_block_auto_pc_0/top_level_block_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_block_auto_pc_0 || ORIG_REF_NAME==top_level_block_auto_pc_0} -quiet] -quiet

# IP: bd/top_level_block/ip/top_level_block_ps8_0_axi_periph_0/top_level_block_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_block_ps8_0_axi_periph_0 || ORIG_REF_NAME==top_level_block_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/top_level_block/ip/top_level_block_gpio_buffer_0_0/top_level_block_gpio_buffer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_block_gpio_buffer_0_0 || ORIG_REF_NAME==top_level_block_gpio_buffer_0_0} -quiet] -quiet

# IP: bd/top_level_block/ip/top_level_block_gpio_buffer_o_0_0/top_level_block_gpio_buffer_o_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_block_gpio_buffer_o_0_0 || ORIG_REF_NAME==top_level_block_gpio_buffer_o_0_0} -quiet] -quiet

# IP: bd/top_level_block/ip/top_level_block_proc_sys_reset_0_1/top_level_block_proc_sys_reset_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_block_proc_sys_reset_0_1 || ORIG_REF_NAME==top_level_block_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/top_level_block/ip/top_level_block_gty_debug_0_1/top_level_block_gty_debug_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_block_gty_debug_0_1 || ORIG_REF_NAME==top_level_block_gty_debug_0_1} -quiet] -quiet

# IP: bd/top_level_block/ip/top_level_block_system_ila_0_0/top_level_block_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_block_system_ila_0_0 || ORIG_REF_NAME==top_level_block_system_ila_0_0} -quiet] -quiet

# IP: bd/top_level_block/ip/top_level_block_system_ila_1_0/top_level_block_system_ila_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_block_system_ila_1_0 || ORIG_REF_NAME==top_level_block_system_ila_1_0} -quiet] -quiet

# XDC: d:/repos/RFSoC_GTY/vivado_project/RFSoC_GTY.gen/sources_1/bd/top_level_block/top_level_block_ooc.xdc
