# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/repos/RFSoC_GTY/vivado_project/RFSoC_GTY.srcs/sources_1/ip/gtwizard_ultrascale_0/gtwizard_ultrascale_0.xci
# IP: The module: 'gtwizard_ultrascale_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/repos/RFSoC_GTY/vivado_project/RFSoC_GTY.gen/sources_1/ip/gtwizard_ultrascale_0/synth/gtwizard_ultrascale_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gtwizard_ultrascale_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/repos/RFSoC_GTY/vivado_project/RFSoC_GTY.gen/sources_1/ip/gtwizard_ultrascale_0/synth/gtwizard_ultrascale_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'gtwizard_ultrascale_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/repos/RFSoC_GTY/vivado_project/RFSoC_GTY.srcs/sources_1/ip/gtwizard_ultrascale_0/gtwizard_ultrascale_0.xci
# IP: The module: 'gtwizard_ultrascale_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/repos/RFSoC_GTY/vivado_project/RFSoC_GTY.gen/sources_1/ip/gtwizard_ultrascale_0/synth/gtwizard_ultrascale_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gtwizard_ultrascale_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/repos/RFSoC_GTY/vivado_project/RFSoC_GTY.gen/sources_1/ip/gtwizard_ultrascale_0/synth/gtwizard_ultrascale_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'gtwizard_ultrascale_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
